apiVersion: v2
name: turing-init
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: v1.0.0
dependencies:
- name: spark-operator
  version: 1.1.7
  repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
