#name: e2e
#
#on:
#  push:
#    paths:
#      - ".github/workflows/e2e.yaml"
#      - "api/**"
#      - "engines/experiment/**"
#      - "engines/router/**"
#      - "infra/**"
#      - "test/e2e/**"
#    branches:
#    - "*"
#  pull_request:
#    branches:
#    - main
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Maximize build space
#      uses: easimon/maximize-build-space@b4d02c14493a9653fe7af06cc89ca5298071c66e
#      with:
#        root-reserve-mb: 40000
#        swap-size-mb: 1024
#        remove-dotnet: 'true'
#        remove-android: 'true'
#        remove-haskell: 'true'
#
#    - name: Check out code
#      uses: actions/checkout@v2
#
#    - name: Set up Go 1.14
#      uses: actions/setup-go@v2
#      with:
#        go-version: "1.14"
#
#    - name: Setup test infra
#      working-directory: test/e2e
#      env:
#        CONCURRENT_NONINTERACTIVE: "1"
#      run: |
#        set -e
#        source setup-infra.sh
#
#        concurrent \
#          - "install_e2e_tools" install_e2e_tools \
#          --and-then \
#          - "install_kubernetes_kind_cluster" install_kubernetes_kind_cluster \
#          --and-then \
#          - "install_local_docker_registry" install_local_docker_registry \
#          - "install_istio" install_istio \
#          --and-then \
#          - "install_knative_serving_with_istio_controller" install_knative_serving_with_istio_controller \
#          - "install_mlp" install_mlp \
#          - "install_vault" install_vault \
#          --and-then \
#          - "install_merlin" install_merlin \
#          - "install_turing" install_turing
#
#    - name: Run test
#      working-directory: api
#      env:
#        TEST_ID: "1"
#        MOCKSERVER_ENDPOINT: http://mockserver
#        API_BASE_PATH: http://turing.127.0.0.1.nip.io/v1
#        MODEL_CLUSTER_NAME: kind
#        PROJECT_ID: "1"
#        PROJECT_NAME: default
#        KUBECONFIG_USE_LOCAL: "true"
#      run: go test -v -parallel=2 ./e2e/... -tags=e2e -run TestEndToEnd
